[build-system]
requires = ["hatchling>=1.20.0"]
build-backend = "hatchling.build"

[project]
name = "or-scenario"
version = "0.3.0"
description = "Template framework for Operations Research scenarios"
authors = [{name = "HerminYakovski", email = "hemin.ye@qq.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.13.4",
    "or-register",
    "data-access-layer[async]",
    "or-algo",
    "omni-orm",
    "pandas>=2.0",
    "openpyxl>=3.0",
]

[tool.uv.sources]
or-register = { index = "testpypi" }
data-access-layer = { index = "testpypi" }
or-algo = { index = "testpypi" }
omni-orm = { index = "testpypi" }

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
explicit = true

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.8",
    "mypy>=1.10",
    "pytest-cov>=7.1.0",
    "pandas-stubs>=2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["or_scenario"]

[tool.coverage.run]
source = ["or_scenario"]

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term-missing --cov-report=html"
filterwarnings = [
    "ignore:.*declarative base already contains.*:sqlalchemy.exc.SAWarning"
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
exclude = ["tests/"]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_ignores = true
